const GET_AVAILABLE_COUNTRIES_PENDING = 'GET_AVAILABLE_COUNTRIES_PENDING'
const GET_AVAILABLE_COUNTRIES_SUCCEED = 'GET_AVAILABLE_COUNTRIES_SUCCEED'
const GET_AVAILABLE_COUNTRIES_FAILED = 'GET_AVAILABLE_COUNTRIES_FAILED'

export {
  GET_AVAILABLE_COUNTRIES_PENDING,
  GET_AVAILABLE_COUNTRIES_SUCCEED,
  GET_AVAILABLE_COUNTRIES_FAILED
}
